import { supabase, isCloudEnabled } from '../../config/supabase';
import type { Team } from '../../engine/types';

// ── Publish / Delete ──────────────────────────────────────────────────────────

// UUID v4 pattern — all IDs generated by this app are UUIDs.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function safeIds(ids: string[]): string[] {
  return ids.filter(id => UUID_RE.test(id));
}

export async function publishTeam(team: Team, ownerPhone?: string | null): Promise<{ success: boolean; error?: string }> {
  if (!isCloudEnabled || !supabase) return { success: false, error: 'Cloud not enabled' };
  try {
    const { error } = await supabase.from('cloud_teams').upsert({
      id: team.id,
      name: team.name,
      short_name: team.shortName,
      latitude: team.latitude,
      longitude: team.longitude,
      ...(ownerPhone ? { owner_phone: ownerPhone } : {}),
      updated_at: Date.now(),
    });
    if (error) throw error;

    // Replace players: delete old, insert new
    await supabase.from('cloud_players').delete().eq('team_id', team.id);
    if (team.players.length > 0) {
      const { error: pe } = await supabase.from('cloud_players').insert(
        team.players.map(p => ({
          id: p.id,
          team_id: team.id,
          name: p.name,
          phone_number: p.phoneNumber ?? null,
          batting_style: p.battingStyle,
          bowling_style: p.bowlingStyle,
          is_wicket_keeper: p.isWicketKeeper,
          is_all_rounder: p.isAllRounder,
          is_captain: p.isCaptain,
          is_vice_captain: p.isViceCaptain,
          jersey_number: p.jerseyNumber ?? null,
          photo_uri: p.photoUri ?? null,
        }))
      );
      if (pe) throw pe;
    }
    return { success: true };
  } catch (err) {
    const message = (err as any)?.message ?? String(err);
    console.error('[cloud-team-repo] publishTeam failed:', message);
    return { success: false, error: message };
  }
}

export async function deleteCloudTeam(teamId: string): Promise<void> {
  if (!isCloudEnabled || !supabase) return;
  try {
    await supabase.from('cloud_teams').delete().eq('id', teamId);
  } catch (err) {
    console.error('[cloud-team-repo] deleteCloudTeam failed:', (err as Error).message);
  }
}

/**
 * Return the IDs of teams whose owner_phone matches the given phone number.
 * Used on login/account-restore to repopulate myTeamIds on a new device.
 */
export async function fetchTeamIdsByOwner(ownerPhone: string): Promise<string[]> {
  if (!isCloudEnabled || !supabase) return [];
  try {
    const { data, error } = await supabase
      .from('cloud_teams')
      .select('id')
      .eq('owner_phone', ownerPhone);
    if (error) {
      if ((error as { code?: string }).code !== 'PGRST205') {
        console.error('[cloud-team-repo] fetchTeamIdsByOwner failed:', error.message);
      }
      return [];
    }
    return (data ?? []).map((r: { id: string }) => r.id);
  } catch (err) {
    console.error('[cloud-team-repo] fetchTeamIdsByOwner failed:', (err as Error).message);
    return [];
  }
}

/**
 * Return the IDs of teams where the given phone number is listed as a player.
 */
export async function fetchTeamIdsByPlayerPhone(playerPhone: string): Promise<string[]> {
  if (!isCloudEnabled || !supabase) return [];
  try {
    const { data, error } = await supabase
      .from('cloud_players')
      .select('team_id')
      .eq('phone_number', playerPhone);
    if (error) {
      if ((error as { code?: string }).code !== 'PGRST205') {
        console.error('[cloud-team-repo] fetchTeamIdsByPlayerPhone failed:', error.message);
      }
      return [];
    }
    return [...new Set((data ?? []).map((r: { team_id: string }) => r.team_id))];
  } catch (err) {
    console.error('[cloud-team-repo] fetchTeamIdsByPlayerPhone failed:', (err as Error).message);
    return [];
  }
}

/**
 * Return the owner_phone for a single team, or null if not found / no owner set.
 * Used during match creation to determine if an invitation is needed.
 */
export async function fetchTeamOwnerPhone(teamId: string): Promise<string | null> {
  if (!isCloudEnabled || !supabase) return null;
  try {
    const { data, error } = await supabase
      .from('cloud_teams')
      .select('owner_phone')
      .eq('id', teamId)
      .single();
    if (error) {
      if ((error as { code?: string }).code !== 'PGRST205' && (error as { code?: string }).code !== 'PGRST116') {
        console.error('[cloud-team-repo] fetchTeamOwnerPhone failed:', error.message);
      }
      return null;
    }
    return (data as any)?.owner_phone ?? null;
  } catch (err) {
    console.error('[cloud-team-repo] fetchTeamOwnerPhone failed:', (err as Error).message);
    return null;
  }
}

// ── Fetch ─────────────────────────────────────────────────────────────────────

export async function fetchTeamsByIds(ids: string[]): Promise<Team[]> {
  if (!isCloudEnabled || !supabase || ids.length === 0) return [];
  try {
    const { data: teamRows, error } = await supabase
      .from('cloud_teams')
      .select('*')
      .in('id', ids);
    if (error) throw error;
    if (!teamRows || teamRows.length === 0) return [];
    return fetchPlayersAndBuild(teamRows);
  } catch (err) {
    console.error('[cloud-team-repo] fetchTeamsByIds failed:', (err as any)?.message ?? err);
    return [];
  }
}

export async function fetchNearbyTeams(
  lat: number,
  lon: number,
  radiusKm: number,
  excludeIds: string[],
): Promise<Team[]> {
  if (!isCloudEnabled || !supabase) return [];
  try {
    const latDelta = radiusKm / 111.0;
    const lonDelta = radiusKm / (111.0 * Math.cos((lat * Math.PI) / 180));

    let teamQuery = supabase
      .from('cloud_teams')
      .select('*')
      .not('latitude', 'is', null)
      .gte('latitude', lat - latDelta)
      .lte('latitude', lat + latDelta)
      .gte('longitude', lon - lonDelta)
      .lte('longitude', lon + lonDelta)
      .limit(50);

    const validExcludeIds = safeIds(excludeIds);
    if (validExcludeIds.length > 0) {
      teamQuery = teamQuery.not('id', 'in', `(${validExcludeIds.join(',')})`);
    }

    const { data: teamRows, error: teamErr } = await teamQuery;
    if (teamErr) throw teamErr;
    if (!teamRows || teamRows.length === 0) return [];

    return fetchPlayersAndBuild(teamRows);
  } catch (err) {
    console.error('[cloud-team-repo] fetchNearbyTeams failed:', (err as any)?.message ?? err);
    return [];
  }
}

export async function searchCloudTeams(
  searchQuery: string,
  excludeIds: string[],
): Promise<Team[]> {
  if (!isCloudEnabled || !supabase) return [];
  // Validate and sanitise search query
  const trimmed = searchQuery.trim().slice(0, 50);
  if (!trimmed) return [];
  // Escape LIKE special characters so user input is treated as a literal string
  const escaped = trimmed.replace(/[%_\\]/g, '\\$&');
  try {
    let teamQuery = supabase
      .from('cloud_teams')
      .select('*')
      .ilike('name', `%${escaped}%`)
      .limit(20);

    const validExcludeIds = safeIds(excludeIds);
    if (validExcludeIds.length > 0) {
      teamQuery = teamQuery.not('id', 'in', `(${validExcludeIds.join(',')})`);
    }

    const { data: teamRows, error: teamErr } = await teamQuery;
    if (teamErr) throw teamErr;
    if (!teamRows || teamRows.length === 0) return [];

    return fetchPlayersAndBuild(teamRows);
  } catch (err) {
    console.error('[cloud-team-repo] searchCloudTeams failed:', (err as any)?.message ?? err);
    return [];
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function fetchPlayersAndBuild(teamRows: any[]): Promise<Team[]> {
  if (!supabase) return [];
  const teamIds = teamRows.map((r: any) => r.id);

  const { data: playerRows, error: playerErr } = await supabase
    .from('cloud_players')
    .select('*')
    .in('team_id', teamIds);

  if (playerErr) {
    console.error('[cloud-team-repo] fetchPlayers failed:', playerErr.message);
  }

  const playersByTeam: Record<string, any[]> = {};
  for (const p of playerRows ?? []) {
    if (!playersByTeam[p.team_id]) playersByTeam[p.team_id] = [];
    playersByTeam[p.team_id].push(p);
  }

  return teamRows.map((row: any) => ({
    id: row.id,
    name: row.name,
    shortName: row.short_name,
    adminPinHash: null,
    latitude: row.latitude ?? null,
    longitude: row.longitude ?? null,
    players: (playersByTeam[row.id] ?? []).map((p: any) => ({
      id: p.id,
      name: p.name,
      phoneNumber: p.phone_number ?? null,
      battingStyle: (p.batting_style ?? 'right') as 'right' | 'left',
      bowlingStyle: p.bowling_style ?? 'none',
      isWicketKeeper: p.is_wicket_keeper ?? false,
      isAllRounder: p.is_all_rounder ?? false,
      isCaptain: p.is_captain ?? false,
      isViceCaptain: p.is_vice_captain ?? false,
      jerseyNumber: p.jersey_number ?? null,
      photoUri: p.photo_uri ?? null,
    })),
    createdAt: row.updated_at ?? Date.now(),
    updatedAt: row.updated_at ?? Date.now(),
  }));
}
